### ISSUE TITLE
:ex_unit_no_meaningful_value error in 12. pattern matching

### ISSUE THREAD

**Issue by quantumpotato** [elixirkoans/elixir-koans#143]
```
Now meditate upon PatternMatching
|==================>           | 114 of 180
----------------------------------------
The pattern can make assertions about what it expects
Assertion failed in lib/koans/12_pattern_matching.ex:49
match?([1, _second, _third], :error)

left:  :ex_unit_no_meaningful_value
right: :error
```

Updated:
```
  koan "The pattern can make assertions about what it expects" do
    assert match?([1, _second, _third], :ex_unit_no_meaningful_value)
  end
```

Result:

```
Now meditate upon PatternMatching
|==================>           | 114 of 180
----------------------------------------
The pattern can make assertions about what it expects
Assertion failed in lib/koans/12_pattern_matching.ex:49
match?([1, _second, _third], :ex_unit_no_meaningful_value)
```

What am I missing here?

**Comment by iamvery** [comment]
It seems like the failure output is not being very helpful in this case. The real failure is that the match failed. This "no meaningful value" thing is an implementation detail of ex unit leaking through. It seems the error output should be improved for assertions that don't have a "left" and "right" side, e.g. `assert left == right`.

The point of this exercise is to recognize that matches can be made against a "pattern" rather than the full content of the data structure. So in this case, the solution is to provide a value to the second argument of `match?/2` that matches the first. Namely, any 3 element list who's first element is `1`.

Does this make sense?

**Comment by quantumpotato** [comment]
Yes, thank you!
