### ISSUE TITLE
"mix meditate" gives Assertion failed error

### ISSUE THREAD

**Issue by dylan-chong** [elixirkoans/elixir-koans#157]
Just installed elixir yesterday with `brew install elixir`. Cloned this repo today and ran `mix deps.get`. Upon running `mix meditate`, this error occurs ("Assertion failed")

```
> mix meditate
warning: variable "deps" does not exist and is being expanded to "deps()", please use parentheses to remove the ambiguity or change the variable name
  mix.exs:9

Welcome to the Elixir koans.
Let these be your first humble steps towards learning a new language.

The path laid in front of you is one of many.


Now meditate upon Equalities
|                              | 0 of 182
----------------------------------------
We shall contemplate truth by testing reality, via equality
Assertion failed in lib/koans/01_equalities.ex:12
true == ___
```

**Comment by dylan-chong** [comment]
Closed because I'm an idiot |:

**Comment by iamvery** [comment]
Hah, you're not an idiot! But I take it you realized this is error is due to a warning that was recently added with Elixir 1.4. For more information, there is a lot of discussion on [the Elixir mailing list](https://groups.google.com/forum/#!topic/elixir-lang-core/Otz0uuML764) as well as [opinion articles](http://iamvery.com/2016/12/05/elixir-deprecation-of-barewords.html).

Thanks for taking the time to help improve things!
