### ISSUE TITLE
Weird chars running in Windows console

### ISSUE THREAD

**Issue by prondzyn** [elixirkoans/elixir-koans#179]
Please take a look at screen shot bellow. I have some weird chars at the the beginning of lines in Windows console. Is it known problem? Is there any solution for this?

![elixir-koans](https://cloud.githubusercontent.com/assets/5822647/23982850/788a2b92-0a10-11e7-9c75-fc3b7d5b643d.png)

**Comment by ukutaht** [comment]
This is because the koans are trying to add color to the output using ANSI escape codes. Your terminal is not recognising the escape sequences and just prints them out literally instead of colorizing the text. I haven't used windows terminals, but you can try to look into ways to have ANSI color code support in the terminal you're using. Alternatively, we can add a command line switch like `mix meditate --no-color` to disable text colors.

**Comment by MrTortoise** [comment]
Alternatively look to conemu or cmder, I bet they have something to get you
what you want.

**Comment by prondzyn** [comment]
@ukutaht thanks, but unfortunately `--no-color` doesn't help

@MrTortoise I downloaded ConEmu. Thanks!
